*Question 3*
*part a*

In [1]:
using Pkg
Pkg.activate("../..")
using LinearAlgebra, CSV, DataFrames, Distributions
Seishi = DataFrame(CSV.File("Seishi.csv"))
Y = Matrix(select(Seishi, r"^y"))
X= Matrix(select(Seishi, r"^x"))
#Add a column of ones to X to get intercept
X = hcat( ones(size(X, 1)),X)
B_hat = (X'X)^-1*X'*Y
display(B_hat)
print("=B_hat")




  Activating project at `~/Documents/Classwork/Spring2026`


9×2 Matrix{Float64}:
 -13.2473      -0.558986
   3.24805      0.381428
  -0.40978     -0.384172
   1.32797      1.45079
   0.171725     0.0117703
   1.10431      0.431534
   0.357364     0.140143
  -0.311593    -0.196143
  -0.00725695  -0.00454939

=B_hat

The first two values are the intercepts for $\hat{y}_1, \hat{y}_2$

*part b*

*i*

$h^TB = \begin{bmatrix} 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1  \end{bmatrix} \begin{bmatrix} b_{1,1}&b_{1,2} \\b_{2,1}&b_{2,2} \\b_{3,1}&b_{3,2} \\b_{4,1}&b_{4,2} \\b_{5,1}&b_{5,2} \\b_{6,1}&b_{6,2} \\b_{7,1}&b_{7,2} \\b_{8,1}&b_{8,2} \\b_{9,1}&b_{9,2} \\ \end{bmatrix} = \vec{0}$

*ii*

In [2]:
h = [0 0 0 0 0 0 0 0 1.0]'
Hₕ = (B_hat'h)*(B_hat'h)'/(h'*(X'X)^-1*h)[1]
display(Hₕ)
E = (Y-X*B_hat)'*(Y-X*B_hat)
display(E)
display(Hₕ*E^-1)

2×2 Matrix{Float64}:
 0.363277  0.227739
 0.227739  0.14277

2×2 Matrix{Float64}:
 1.10751   0.438385
 0.438385  0.705697

2×2 Matrix{Float64}:
 0.265575  0.157737
 0.16649   0.0988854

$H_hE^{-1} = \begin{bmatrix} .266 & .158 \\ .166 & .099\end{bmatrix}$

*iii*

In [3]:
λ₁ = ((B_hat'*h)'*E^-1*(B_hat'*h))[1]/(h'*(X'X)^-1*h)[1]
display(λ₁)
display(eigen(Hₕ*E^-1).values[2])

0.3644607988821039

0.364460798882104

Here we can see a bit of error from floating point arithmetic, but the two values are the same. Just like in the univariate case, $\lambda_1$ is F distributed, but since we're estimated two means (taste and aroma), we now have to consider d, the number of means per row. In our case it two, so $\lambda_1 \frac{17-2-8-1}{2}\sim F_{2, 17 - 2- 8-1}$

*iv*

In [4]:
f_dist = FDist(2, 6)

# Step 3: Calculate the p-value
# The p-value is computed as 1 - CDF(f_dist, critical_value)
p_value = 1-cdf(f_dist, λ₁ * 3)

println("The p-value is: ", p_value)


The p-value is: 0.3936559421776993


The p value is well above .05, so we fail to reject the null 

*Part C*

*i*
The only thing that changes from part B is the hypothesis matrix

$h^TB = \begin{bmatrix} 0 & 0 & 1 & -1 & 0 & 0 & 0 & 0 & 0  \end{bmatrix} \begin{bmatrix} b_{1,1}&b_{1,2} \\b_{2,1}&b_{2,2} \\b_{3,1}&b_{3,2} \\b_{4,1}&b_{4,2} \\b_{5,1}&b_{5,2} \\b_{6,1}&b_{6,2} \\b_{7,1}&b_{7,2} \\b_{8,1}&b_{8,2} \\b_{9,1}&b_{9,2} \\ \end{bmatrix} = \vec{0}$

*ii*

In [5]:
h = [0 0 1.0 -1.0 0 0 0 0 0]'
Hₕ = (B_hat'h)*(B_hat'h)'/(h'*(X'X)^-1*h)[1]
display(Hₕ)
E = (Y-X*B_hat)'*(Y-X*B_hat)
display(E)
display(Hₕ*E^-1)

2×2 Matrix{Float64}:
 0.133837  0.141324
 0.141324  0.149229

2×2 Matrix{Float64}:
 1.10751   0.438385
 0.438385  0.705697

2×2 Matrix{Float64}:
 0.0551322  0.166013
 0.0582163  0.175299

$H_hE^{-1} = \begin{bmatrix} .055 & .166 \\ .058 & .175\end{bmatrix}$

*iii*

In [6]:
λ₁ = ((B_hat'*h)'*E^-1*(B_hat'*h))[1]/(h'*(X'X)^-1*h)[1]
display(λ₁)
display(eigen(Hₕ*E^-1).values[2])

0.23043146386742747

0.2304314638674275

Again, we see that the values are the same accounting for floating point arithmetic error

In [7]:
f_dist = FDist(2, 6)

# Step 3: Calculate the p-value
# The p-value is computed as 1 - CDF(f_dist, critical_value)
p_value = 1-cdf(f_dist, λ₁ * 3)

println("The p-value is: ", p_value)


The p-value is: 0.536818798424264


Again, the p value is well above .05 so we fail to reject the null (that acidity 1 has a different effect than acidity 2)